# Dataset
ds_name: dubosson2018
data_csv_path: ./raw_data/Dubosson2018_processed.csv
index_col: -1
observation_interval: 5min

# Columns
column_definition:
  - name: id
    data_type: categorical
    input_type: id
  - name: time
    data_type: date
    input_type: time
  - name: gl
    data_type: real_valued
    input_type: target

# Drop
drop:
  rows: null
  columns:
    id:
      - 9

# NA values abbreviation
nan_vals: null

# Interpolation parameters
interpolation_params:
  gap_threshold: 30 # in minutes
  min_drop_length: 240 # number of points

# Splitting parameters
split_params:
  test_percent_subjects: 0.1
  length_segment: 240
  random_state: 0

# Encoding parameters
encoding_params:
  date: 
    - year
    - month
    - day
    - hour
    - minute

# Scaling parameters
scaling_params:
  scaler: None

# Model params
max_length_input: 192
length_pred: 12