# Dataset
ds_name: weinstock2016
data_csv_path: ./raw_data/Weinstock2016_processed.csv
index_col: -1
observation_interval: 5min

# Columns
column_definition:
  - name: id
    data_type: categorical
    input_type: id
  - name: time
    data_type: date
    input_type: time
  - name: gl
    data_type: real_valued
    input_type: target

# Drop
drop: 
  id:
    - 9

# Interpolation parameters
interpolation_params:
  gap_threshold: 45
  min_drop_length: 20

# Splitting parameters
split_params:
  test_percent_subjects: 0.1
  length_segment: 192

# Encoding parameters
encoding_params:
  date: 
    - year
    - month
    - day
    - hour
    - minute

# Scaling parameters
scaling_params:
  scale_by: id
  scaler: StandardScaler
  